/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package notifications

import (
	"strings"
	"sync"
	"testing"

	"github.com/stretchr/testify/assert"

	istioclientv1beta1 "istio.io/client-go/pkg/apis/networking/v1beta1"
	networkingv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
	gatewayv1 "sigs.k8s.io/gateway-api/apis/v1"
)

func TestReportRender(t *testing.T) {
	testCases := []struct {
		name     string
		setup    func(r *Report)
		expected string
	}{
		{
			name:     "no notifications",
			setup:    func(_ *Report) {},
			expected: "",
		},
		{
			name: "single source with one notification",
			setup: func(r *Report) {
				r.Add("provider1", Notification{
					Type:    WarningNotification,
					Message: "warning message",
				})
			},
			expected: `┌─ WARN  ────────────────────────────────────────
│  warning message
│  source: PROVIDER1
└─
`,
		},
		{
			name: "two sources each with two notifications",
			setup: func(r *Report) {
				r.Add("istio", Notification{
					Type:    WarningNotification,
					Message: "a very long warning notification generated by VirtualService ns/test from the provider istio",
					CallingObjects: []client.Object{
						&istioclientv1beta1.VirtualService{
							TypeMeta: metav1.TypeMeta{
								Kind: "VirtualService",
							},
							ObjectMeta: metav1.ObjectMeta{
								Name:      "test",
								Namespace: "ns",
							},
						},
					},
				})
				r.Add("istio", Notification{
					Type:    InfoNotification,
					Message: "successfully converted VirtualService ns/test to HTTPRoute",
					CallingObjects: []client.Object{
						&istioclientv1beta1.VirtualService{
							TypeMeta: metav1.TypeMeta{
								Kind: "VirtualService",
							},
							ObjectMeta: metav1.ObjectMeta{
								Name:      "test",
								Namespace: "ns",
							},
						},
					},
				})
				r.Add("kong", Notification{
					Type:    InfoNotification,
					Message: "informational notification from kong provider",
					CallingObjects: []client.Object{
						&networkingv1.Ingress{
							TypeMeta: metav1.TypeMeta{
								Kind: "Ingress",
							},
							ObjectMeta: metav1.ObjectMeta{
								Name:      "ingress-kong",
								Namespace: "default",
							},
						},
					},
				})
				r.Add("kong", Notification{
					Type:    ErrorNotification,
					Message: "error notification genereated by kong",
				})
			},
			expected: `┌─ WARN  ────────────────────────────────────────
│  a very long warning notification generated by VirtualService ns/test from the provider istio
│  source: ISTIO
│  object: VirtualService: ns/test
└─
┌─ INFO  ────────────────────────────────────────
│  successfully converted VirtualService ns/test to HTTPRoute
│  source: ISTIO
│  object: VirtualService: ns/test
└─
┌─ INFO  ────────────────────────────────────────
│  informational notification from kong provider
│  source: KONG
│  object: Ingress: default/ingress-kong
└─
┌─ ERROR ────────────────────────────────────────
│  error notification genereated by kong
│  source: KONG
└─
`,
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			r := NewReport(true)
			tc.setup(r)
			result := r.Render()
			assert.Equal(t, tc.expected, result)
		})
	}
}

// TestReportConcurrentAdd checks for data races in Report when accessed concurrently.
func TestReportConcurrentAdd(t *testing.T) {
	r := NewReport(true)

	providers := []string{"provider1", "provider2", "provider3", "provider4"}
	var wg sync.WaitGroup

	// Start multiple goroutines that add notifications concurrently.
	for _, provider := range providers {
		wg.Go(func() {
			for range 100 {
				r.Add(provider, Notification{
					Type:    WarningNotification,
					Message: "concurrent warning",
				})
			}
		})
	}

	// Concurrently read from the report while writes are happening.
	wg.Go(func() {
		for range 100 {
			_ = r.Render()
		}
	})

	wg.Wait()

	// Verify all notifications were recorded.
	result := r.Render()
	for _, provider := range providers {
		assert.Equal(t, 100, strings.Count(result, "source: "+strings.ToUpper(provider)))
	}
}

func TestReportNotifier(t *testing.T) {
	r := NewReport(true)
	notify := r.Notifier("test-provider")

	ingress := &networkingv1.Ingress{
		TypeMeta: metav1.TypeMeta{Kind: "Ingress"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "my-ingress",
			Namespace: "default",
		},
	}

	gateway := &gatewayv1.Gateway{
		TypeMeta: metav1.TypeMeta{Kind: "Gateway"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "my-gw",
			Namespace: "prod",
		},
	}

	notify(WarningNotification, "host not supported")
	notify(InfoNotification, "converted successfully", ingress)
	notify(ErrorNotification, "multiple objects involved", ingress, gateway)

	result := r.Render()
	assert.Contains(t, result, "source: TEST-PROVIDER")
	assert.Contains(t, result, "WARN")
	assert.Contains(t, result, "host not supported")
	assert.Contains(t, result, "INFO")
	assert.Contains(t, result, "converted successfully")
	assert.Contains(t, result, "Ingress: default/my-ingress")
	assert.Contains(t, result, "ERROR")
	assert.Contains(t, result, "multiple objects involved")
	assert.Contains(t, result, "Gateway: prod/my-gw")
}

// Ensure notifications don't "leak" between sources.
func TestReportNotifierScoping(t *testing.T) {
	r := NewReport(true)

	notifyA := r.Notifier("providerA")
	notifyB := r.Notifier("providerB")

	notifyA(InfoNotification, "msg from A")
	notifyB(WarningNotification, "msg from B")

	result := r.Render()
	assert.Contains(t, result, "msg from A")
	assert.Contains(t, result, "source: PROVIDERA")
	assert.Contains(t, result, "msg from B")
	assert.Contains(t, result, "source: PROVIDERB")
}
