/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package notifications

import (
	"strings"
	"sync"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	istioclientv1beta1 "istio.io/client-go/pkg/apis/networking/v1beta1"
	networkingv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
	gatewayv1 "sigs.k8s.io/gateway-api/apis/v1"
)

func TestReportRender(t *testing.T) {
	testCases := []struct {
		name     string
		setup    func(r *Report)
		expected map[string]string
	}{
		{
			name:     "no notifications",
			setup:    func(_ *Report) {},
			expected: map[string]string{},
		},
		{
			name: "single source with one notification",
			setup: func(r *Report) {
				r.Add("provider1", Notification{
					Type:    WarningNotification,
					Message: "warning message",
				})
			},
			expected: map[string]string{
				"provider1": `Notifications from PROVIDER1:
+--------------+-----------------+----------------+
| MESSAGE TYPE |  NOTIFICATION   | CALLING OBJECT |
+--------------+-----------------+----------------+
| WARNING      | warning message |                |
+--------------+-----------------+----------------+
`,
			},
		},
		{
			name: "two sources each with two notifications",
			setup: func(r *Report) {
				r.Add("istio", Notification{
					Type:    WarningNotification,
					Message: "a very long warning notification generated by VirtualService ns/test from the provider istio",
					CallingObjects: []client.Object{
						&istioclientv1beta1.VirtualService{
							TypeMeta: metav1.TypeMeta{
								Kind: "VirtualService",
							},
							ObjectMeta: metav1.ObjectMeta{
								Name:      "test",
								Namespace: "ns",
							},
						},
					},
				})
				r.Add("istio", Notification{
					Type:    InfoNotification,
					Message: "successfully converted VirtualService ns/test to HTTPRoute",
					CallingObjects: []client.Object{
						&istioclientv1beta1.VirtualService{
							TypeMeta: metav1.TypeMeta{
								Kind: "VirtualService",
							},
							ObjectMeta: metav1.ObjectMeta{
								Name:      "test",
								Namespace: "ns",
							},
						},
					},
				})
				r.Add("kong", Notification{
					Type:    InfoNotification,
					Message: "informational notification from kong provider",
					CallingObjects: []client.Object{
						&networkingv1.Ingress{
							TypeMeta: metav1.TypeMeta{
								Kind: "Ingress",
							},
							ObjectMeta: metav1.ObjectMeta{
								Name:      "ingress-kong",
								Namespace: "default",
							},
						},
					},
				})
				r.Add("kong", Notification{
					Type:    ErrorNotification,
					Message: "error notification genereated by kong",
				})
			},
			expected: map[string]string{
				"istio": `Notifications from ISTIO:
+--------------+----------------------------------------------------------------------------------------------+-------------------------+
| MESSAGE TYPE |                                         NOTIFICATION                                         |     CALLING OBJECT      |
+--------------+----------------------------------------------------------------------------------------------+-------------------------+
| WARNING      | a very long warning notification generated by VirtualService ns/test from the provider istio | VirtualService: ns/test |
+--------------+----------------------------------------------------------------------------------------------+-------------------------+
| INFO         | successfully converted VirtualService ns/test to HTTPRoute                                   | VirtualService: ns/test |
+--------------+----------------------------------------------------------------------------------------------+-------------------------+
`,
				"kong": `Notifications from KONG:
+--------------+-----------------------------------------------+-------------------------------+
| MESSAGE TYPE |                 NOTIFICATION                  |        CALLING OBJECT         |
+--------------+-----------------------------------------------+-------------------------------+
| INFO         | informational notification from kong provider | Ingress: default/ingress-kong |
+--------------+-----------------------------------------------+-------------------------------+
| ERROR        | error notification genereated by kong         |                               |
+--------------+-----------------------------------------------+-------------------------------+
`,
			},
		},
	}

	for _, tc := range testCases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			r := NewReport()
			tc.setup(r)
			result := r.Render()
			for provider, table := range result {
				assert.Equal(t, tc.expected[provider], table)
			}
		})
	}
}

// TestReportConcurrentAdd checks for data races in Report when accessed concurrently.
func TestReportConcurrentAdd(t *testing.T) {
	r := NewReport()

	providers := []string{"provider1", "provider2", "provider3", "provider4"}
	var wg sync.WaitGroup

	// Start multiple goroutines that add notifications concurrently.
	for _, provider := range providers {
		wg.Go(func() {
			for range 100 {
				r.Add(provider, Notification{
					Type:    WarningNotification,
					Message: "concurrent warning",
				})
			}
		})
	}

	// Concurrently read from the report while writes are happening.
	wg.Go(func() {
		for range 100 {
			_ = r.Render()
		}
	})

	wg.Wait()

	// Verify all notifications were recorded.
	result := r.Render()
	require.Len(t, result, len(providers))
	for _, provider := range providers {
		table := result[provider]
		count := strings.Count(table, "concurrent warning")
		assert.Equal(t, 100, count, "provider %s should have exactly 100 notifications", provider)
	}
}

func TestReportNotifier(t *testing.T) {
	r := NewReport()
	notify := r.Notifier("test-provider")

	ingress := &networkingv1.Ingress{
		TypeMeta: metav1.TypeMeta{Kind: "Ingress"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "my-ingress",
			Namespace: "default",
		},
	}

	gateway := &gatewayv1.Gateway{
		TypeMeta: metav1.TypeMeta{Kind: "Gateway"},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "my-gw",
			Namespace: "prod",
		},
	}

	notify(WarningNotification, "host not supported")
	notify(InfoNotification, "converted successfully", ingress)
	notify(ErrorNotification, "multiple objects involved", ingress, gateway)

	tables := r.Render()
	require.Contains(t, tables, "test-provider")

	table := tables["test-provider"]
	assert.Contains(t, table, "Notifications from TEST-PROVIDER:")
	assert.Contains(t, table, "WARNING")
	assert.Contains(t, table, "host not supported")
	assert.Contains(t, table, "INFO")
	assert.Contains(t, table, "converted successfully")
	assert.Contains(t, table, "Ingress: default/my-ingress")
	assert.Contains(t, table, "ERROR")
	assert.Contains(t, table, "multiple objects involved")
	assert.Contains(t, table, "Gateway: prod/my-gw")
}

// Ensure notifications don't "leak" between sources.
func TestReportNotifierScoping(t *testing.T) {
	r := NewReport()

	notifyA := r.Notifier("providerA")
	notifyB := r.Notifier("providerB")

	notifyA(InfoNotification, "msg from A")
	notifyB(WarningNotification, "msg from B")

	tables := r.Render()
	require.Len(t, tables, 2)
	require.Contains(t, tables, "providerA")
	require.Contains(t, tables, "providerB")

	assert.Contains(t, tables["providerA"], "msg from A")
	assert.NotContains(t, tables["providerA"], "msg from B")

	assert.Contains(t, tables["providerB"], "msg from B")
	assert.NotContains(t, tables["providerB"], "msg from A")
}
