version: "2"
run:
  go: "1.25"
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: false
linters:
  # Start from no linters and explicitly enable what you care about.
  default: none
  enable:
    - revive
    - govet
    - misspell
    - unused
  # Settings for linters (v2: moved here from `linters-settings`)
  settings:
    govet:
      shadow: true
    misspell:
      locale: US
    gosec:
      excludes:
        - G115
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: var-naming
          disabled: true
formatters:
  # In v2, gofmt/goimports live under "formatters", not "linters.enable"
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
issues:
  exclude-rules:
    # Same as before: skip some linters on *_test.go
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
  exclude:
    - Using the variable on range scope `tc` in function literal
