version: "2"
run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: false

linters:
  default: standard
  enable:
    - revive
    - govet
    - misspell
    # bugs presets
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - zerologlint
    # unused presets
    - ineffassign
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    govet:
      # report about shadowed variables
      enable:
        - shadow
    misspell:
      locale: US
    # (rkatz) - Added as we have a couple of APIs conversion (eg Istio, Kong) that convert uint->int and there's no solution
    gosec:
      excludes:
        - G115
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      # Exclude some linters from running on tests files.
      - path: '_test\.go'
        linters:
          - gocyclo
          - errcheck
          - dupl
      # Exclude gosec G104 (unhandled errors) from test files
      - path: '_test\.go'
        linters:
          - gosec
        text: "G104"
      # Allow underscores in emitter package names
      - path: pkg/i2gw/emitters/
        linters:
          - revive
        text: "var-naming: don't use an underscore in package name"
      - path: '(.+)\.go$'
        text: "Using the variable on range scope `tc` in function literal"
      # Allow capitalized error messages
      - linters:
          - staticcheck
        text: "ST1005:"
      # Allow embedded field, currently this style is used in many places
      - linters:
          - staticcheck
        text: "QF1008:"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      # simplify code: gofmt with `-s` option, true by default
      simplify: true
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
