run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  exclude-dirs-use-default: true
  modules-download-mode: readonly
  allow-parallel-runners: false

linters:
  fast: false
  enable:
  - gofmt
  - goimports
  - revive
  - govet
  - misspell
  disable-all: false
  presets:
  - bugs
  - unused

# all available settings of specific linters
linters-settings:
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  golint:
    min-confidence: 0.9
  govet:
    # report about shadowed variables
    shadow: true
  misspell:
    locale: US
  # (rkatz) - Added as we have a couple of APIs conversion (eg Istio, Kong) that convert uint->int and there's no solution
  gosec:
    excludes:
      - G115

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
  exclude:
    - Using the variable on range scope `tc` in function literal
