apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple
spec:
  rules:
  - host: some.test
    http:
      paths:
      - backend:
          service:
            name: backend
            port:
              number: 3000
        path: /
        pathType: Exact