name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: GoReleaser - Release
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: build --snapshot --clean

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
